AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart Data Stack

Parameters:

  Environment:
    Type: String
    Default: dev

  DBName:
    Type: String
    Default: cloudmart

  DBUsername:
    Type: String
    Default: cloudmartadmin

  DBPassword:
    Type: String
    NoEcho: true

Resources:

  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudMart RDS subnet group
      SubnetIds:
        - Fn::ImportValue:
            !Sub CloudMart-${Environment}-PrivateSubnetId
        - Fn::ImportValue:
            !Sub CloudMart-${Environment}-PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub cloudmart-rds-subnet-group-${Environment}

  CloudMartRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub cloudmart-mysql-${Environment}
      Engine: mysql
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp3
      Port: 3306
      PubliclyAccessible: false
      MultiAZ: false
      DBSubnetGroupName: !Ref RdsSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Sub CloudMart-${Environment}-RdsSecurityGroupId
      BackupRetentionPeriod: 1
      DeletionProtection: false
      DeleteAutomatedBackups: true
      Tags:
        - Key: Name
          Value: !Sub cloudmart-rds-${Environment}

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub cloudmart-artifacts-${Environment}

  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub cloudmart-reports-${Environment}

Outputs:

  RdsEndpoint:
    Value: !GetAtt CloudMartRDS.Endpoint.Address
    Export:
      Name: !Sub CloudMart-${Environment}-RdsEndpoint

  RdsPort:
    Value: !GetAtt CloudMartRDS.Endpoint.Port
    Export:
      Name: !Sub CloudMart-${Environment}-RdsPort

  ArtifactsBucketName:
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub CloudMart-${Environment}-ArtifactsBucketName

  ReportsBucketName:
    Value: !Ref ReportsBucket
    Export:
      Name: !Sub CloudMart-${Environment}-ReportsBucketName