name: CloudMart Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'cloudformation/**'
      - '.github/workflows/deploy.yaml'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ENVIRONMENT: dev

jobs:

  # ==========================================================
  # NETWORK
  # ==========================================================

  deploy-network:
    name: Deploy Network Stack
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Network Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/network-stack.yaml \
            --stack-name cloudmart-network-${{ env.ENVIRONMENT }} \
            --parameter-overrides \
              Environment=${{ env.ENVIRONMENT }} \
            --capabilities CAPABILITY_NAMED_IAM


  # ==========================================================
  # DATA
  # ==========================================================

  deploy-data:
    name: Deploy Data Stack
    needs: deploy-network
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Data Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/data-stack.yaml \
            --stack-name cloudmart-data-${{ env.ENVIRONMENT }} \
            --parameter-overrides \
              Environment=${{ env.ENVIRONMENT }} \
              DBUsername=${{ secrets.DB_USERNAME }} \
              DBPassword=${{ secrets.DB_PASSWORD }} \
            --capabilities CAPABILITY_NAMED_IAM


  # ==========================================================
  # AUTH
  # ==========================================================

  deploy-auth:
    name: Deploy Auth Stack
    needs: deploy-data
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Auth Stack
 run: |
    aws cloudformation deploy \
      --template-file cloudformation/auth-stack.yaml \
      --stack-name cloudmart-auth-dev \
      --parameter-overrides \
        Environment=dev \
        AuthToken="${{ secrets.CLOUDMART_AUTH_TOKEN }}" \
      --capabilities CAPABILITY_NAMED_IAM